# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  reportes:
    output: true

# mapbox
mapbox-token: pk.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mapbox-id: xxxxxxxx.xxxxxxxx

#flickr
flickr:
	cache_dir: 		"./_cache/flickr"
	api_key: 		xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	shared_secret: 	xxxxxxxxxxxxxxxx
	access_token: 	xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx
	access_secret: 	xxxxxxxxxxxxxxxx